"""empty message

Revision ID: 44b503407fee
Revises: 514633d38f49
Create Date: 2023-04-29 11:30:22.485904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b503407fee'
down_revision = '514633d38f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
